kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: {{ .Values.template.metadata.bananahpa }}
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.template.metadata.bananaapp }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.resources.targetAverageUtilization }}
