apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.template.metadata.helloworldapp }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.template.metadata.helloworldapp }}
  template:
    metadata:
      labels:
        app: {{ .Values.template.metadata.helloworldapp }}
    spec:
      containers:
      - name: {{ .Values.template.containername.helloworldcontainer }}
        image: {{ .Values.imagenames.helloworld }}
        ports:
        - containerPort: {{ .Values.ports.helloworldinsideclusterport }}
        resources:
          limits:
            cpu: {{ .Values.resources.limitcpu }}
            memory: {{ .Values.resources.limitmemory }}
          requests:
            cpu: {{ .Values.resources.requestscpu }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.template.metadata.helloworldsvc }}
spec:
  type: {{ .Values.Service.helloworldtype }}
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: {{ .Values.ports.helloworldinsideclusterport }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.ports.helloworldtargetPort }}
      # Port accessible outside cluster
  selector:
    app: {{ .Values.template.metadata.helloworldapp }}
