kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: helloworldhpa
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
