apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.template.metadata.helloworldsvc }}
spec:
  type: {{ .Values.Service.helloworldtype }}
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: {{ .Values.ports.helloworldinsideclusterport }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.ports.helloworldtargetPort }}
      # Port accessible outside cluster
  selector:
    app: {{ .Values.template.metadata.helloworldapp }}
