apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-app
spec:
  selector:
    matchLabels:
      app: apple-app
  template:
    metadata:
      labels:
        app: apple-app
    spec:
      containers:
        - name: apple-app
          image: hashicorp/http-echo
          args:
            - "-text=apple"
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
            requests:
              cpu: 100m
---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  type: ClusterIP
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image
