kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: applehpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apple-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
