apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-app
spec:
  selector:
    matchLabels:
      app: banana-app
  template:
    metadata:
      labels:
        app: banana-app
    spec:
      containers:
        - name: banana-app
          image: hashicorp/http-echo
          args:
            - "-text=banana"
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
            requests:
              cpu: 100m
---

apiVersion: v1
kind: Service
metadata:
  name: banana-service
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 5678
      # Port to forward to inside the pod
      targetPort: 5678
  selector:
    app: banana-app
