kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: nginxhpa
  namespace: ingress-nginx
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-ingress-controller
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
